#!/bin/bash
num_of_args=$#

if [ $num_of_args -eq 2 ]; then

    python module/simulateNanoSeqs/ont_error_simulator.py --read-file $1 --sim-file $2 --badread-error-model nanopore2023 --badread-qscore-model nanopore2023 --badread-identity 95,5,99 --thread 8
        

else
  echo "Usage: bash $0 *.fasta *.fasta. The first fasta file contains the reference sequences and the second fasta file is the simulated data generated by the first fasta file."
  echo "Basic error model: 'nanopore2023' (https://github.com/rrwick/Badread.git) in Badread package."
fi
 